services:
  app:
    build:
      context: .
      target: dev
    volumes:
      - ./src:/usr/src/app/src # Sync source code
      - ./dist:/usr/src/app/dist # Sync compiled output
      - ./tsconfig.json:/usr/src/app/tsconfig.json # Sync tsconfig.json
      - /usr/src/app/node_modules # Ensure node_modules remain container-local
    environment:
      NODE_ENV: development
    env_file:
      - .env
